---
- name: Site Down
  hosts: web
  vars_files: 
    - token.yml
  gather_facts: true
  become: true
  tasks:
    - name: Print message
      debug:
        msg: "Website is down!"

    - name: Get the status of Apache service
      shell: "systemctl status httpd"
      register: httpd_status

    - name: Create ticket on Jira for website down
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: '{{my_username}}'
        password: '{{my_password}}'
        project: AN
        operation: create
        account_id: '712020:15bec00b-c156-4698-a964-8c125cb05fc0'
        summary: "Website is down on server '{{ ansible_default_ipv4.address }}'"
        description: "Hello Team,\n
        The website is down on the server: '{{ ansible_default_ipv4.address }}'\n
        We are trying to resolve the issue!\n
        Below is the status of HTTPD service:\n
        '{{httpd_status.stdout_lines}}'\n


        Thanks and Regards,\n
        Ansible"
        issuetype: '[System] Incident'
      register: issue
    
    - name: Comment on issue
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: '{{my_username}}'
        password: '{{my_password}}'
        issue: '{{ issue.meta.key }}'
        operation: comment
        comment: "Hi Team,\n
        We have received an alert for Website down on this server '{{ ansible_default_ipv4.address }}'.\n
        We are trying to resolve the issue by adding http port in firewall and taking httpd service restart\n


        Thanks and Regards,\n
        Ansible"

    - name: "Ensure firewall openings are in place."
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: "Restart apache webserver"
      service:
        name: httpd
        state: restarted

    - name: Comment on issue
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: '{{my_username}}'
        password: '{{my_password}}'
        issue: '{{ issue.meta.key }}'
        operation: comment
        comment: "Hi Team,\n 
        We have taken the Apache server restart and added the port to firewall.\n
        Below is the status of HTTPD service:\n
        '{{httpd_status.stdout_lines}}'\n

        Hence, moving forward to resolve the issue!



        Thanks and Regards,\n
        Ansible"

    - name: Resolve the issue
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: '{{my_username}}'
        password: '{{my_password}}'
        issue: '{{ issue.meta.key }}'
        operation: transition
        status: 'Resolve' 
