---
- name: Site Down
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Print message
      debug:
        msg: "Website is down!"

    - name: Create ticket on Jira for website down
      community.general.jira:
        uri: 'https://agnel.atlassian.net'
        username: 'agnel.raja@wysetek.com'
        password: 'ATATT3xFfGF08cYOlCUIsrGO9Gqoogk4I2ALHZihqBpyunGAsHt3hKxyzHcHKlesdmxWqiThcAvqXZ6MHvBts3OK6XzX9lxdxBrK_TxGrjE53-_BUjvDyJ6XSKeFEKNYxbXS1-WW0nwvpWSh9iFZZ93zqZbbAj-Ap4j9M5rr8Td7TojQ79J0SnU=D454826E'
        project: AUT
        operation: create
        account_id: '712020:15bec00b-c156-4698-a964-8c125cb05fc0'
        summary: "Website is down on server '{{ ansible_default_ipv4.address }}'"
        description: "Hello Team,\n
        The website is down on the server: '{{ ansible_default_ipv4.address }}'\n
        We are trying to resolve the issue!\n


        Thanks and Regards,\n
        Ansible"
        issuetype: '[System] Incident'
      register: issue
    
    - name: Comment on issue
      community.general.jira:
        uri: 'https://agnel.atlassian.net'   
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0xME2CG6prqR6nDy7iolsCirA6dOof_IP39ofv6XJnFLMZ9TxgOjotg5IO0SAH-DztdVH644aZmL4JgkpsjjMKl_HJt97E-XW6O1xIhYKYopP_pox9qosXMibMuw7Gr4V4KKTUVpR2HbYegm6HHmXzPC51Gzt8_VbKd7PKdMxCYY=94A77412'
        issue: '{{ issue.meta.key }}'
        operation: comment
        comment: "Hi team,\n
        We have received an alert for Website down on this server '{{ ansible_default_ipv4.address }}'.\n
        We are trying to resolve the issue by adding http port in firewall and taking httpd service restart\n


        Thanks and Regards\n
        Ansible"

    - name: "Ensure firewall openings are in place."
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: "Restart apache webserver"
      service:
        name: httpd
        state: restarted

    - name: Comment on issue
      community.general.jira:
        uri: 'https://agnel.atlassian.net'
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0xME2CG6prqR6nDy7iolsCirA6dOof_IP39ofv6XJnFLMZ9TxgOjotg5IO0SAH-DztdVH644aZmL4JgkpsjjMKl_HJt97E-XW6O1xIhYKYopP_pox9qosXMibMuw7Gr4V4KKTUVpR2HbYegm6HHmXzPC51Gzt8_VbKd7PKdMxCYY=94A77412'
        issue: '{{ issue.meta.key }}'
        operation: comment
        comment: "Hi team,\n 
        We have taken the Apache server restart and added the port to firewall and going forward to resolve the issue. \n


        Thanks and Regards,\n
        Ansible"

    - name: Resolve the issue
      community.general.jira:
        uri: 'https://agnel.atlassian.net'
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0xME2CG6prqR6nDy7iolsCirA6dOof_IP39ofv6XJnFLMZ9TxgOjotg5IO0SAH-DztdVH644aZmL4JgkpsjjMKl_HJt97E-XW6O1xIhYKYopP_pox9qosXMibMuw7Gr4V4KKTUVpR2HbYegm6HHmXzPC51Gzt8_VbKd7PKdMxCYY=94A77412'
        issue: '{{ issue.meta.key }}'
        operation: transition
        status: 'Resolve' 
