---
- name: Site Down
  hosts: web
  gather_facts: true
  become: true
  tasks:
    - name: Print message
      debug:
        msg: "Website is down!"

    - name: Create ticket on Jira for website down
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0U-7_QtWyEZJ4Ykfz9H7MQJ7-gYAgxq8bUH-ojixZa2JS3O1BU5oc6HTgnZ9hIwdmAjyTa-Zw2erUtgc62Fj8qqAiDblH0VmN83cQh6rZWFVR-SqVoV2yogk3Q9koUd_tZW-08m6j3b8ywK__fErXS29e3QgyUrk4LQ4cYvO5NSQ=74BE4348'
        project: AN
        operation: create
        account_id: '712020:15bec00b-c156-4698-a964-8c125cb05fc0'
        summary: "Website is down on server '{{ ansible_default_ipv4.address }}'"
        description: "Hello Team,\n
        The website is down on the server: '{{ ansible_default_ipv4.address }}'\n
        We are trying to resolve the issue!\n


        Thanks and Regards,\n
        Ansible"
        issuetype: '[System] Incident'
      register: issue
    
    - name: Comment on issue
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0U-7_QtWyEZJ4Ykfz9H7MQJ7-gYAgxq8bUH-ojixZa2JS3O1BU5oc6HTgnZ9hIwdmAjyTa-Zw2erUtgc62Fj8qqAiDblH0VmN83cQh6rZWFVR-SqVoV2yogk3Q9koUd_tZW-08m6j3b8ywK__fErXS29e3QgyUrk4LQ4cYvO5NSQ=74BE4348'
        issue: '{{ issue.meta.key }}'
        operation: comment
        comment: "Hi Team,\n
        We have received an alert for Website down on this server '{{ ansible_default_ipv4.address }}'.\n
        We are trying to resolve the issue by adding http port in firewall and taking httpd service restart\n


        Thanks and Regards,\n
        Ansible"

    - name: "Ensure firewall openings are in place."
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: "Restart apache webserver"
      service:
        name: httpd
        state: restarted

    - name: Comment on issue
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0U-7_QtWyEZJ4Ykfz9H7MQJ7-gYAgxq8bUH-ojixZa2JS3O1BU5oc6HTgnZ9hIwdmAjyTa-Zw2erUtgc62Fj8qqAiDblH0VmN83cQh6rZWFVR-SqVoV2yogk3Q9koUd_tZW-08m6j3b8ywK__fErXS29e3QgyUrk4LQ4cYvO5NSQ=74BE4348'
        issue: '{{ issue.meta.key }}'
        operation: comment
        comment: "Hi Team,\n 
        We have taken the Apache server restart and added the port to firewall and going forward to resolve the issue. \n


        Thanks and Regards,\n
        Ansible"

    - name: Resolve the issue
      community.general.jira:
        uri: 'https://ashvini-chavan.atlassian.net/'
        username: 'platformansible@gmail.com'
        password: 'ATATT3xFfGF0U-7_QtWyEZJ4Ykfz9H7MQJ7-gYAgxq8bUH-ojixZa2JS3O1BU5oc6HTgnZ9hIwdmAjyTa-Zw2erUtgc62Fj8qqAiDblH0VmN83cQh6rZWFVR-SqVoV2yogk3Q9koUd_tZW-08m6j3b8ywK__fErXS29e3QgyUrk4LQ4cYvO5NSQ=74BE4348'
        issue: '{{ issue.meta.key }}'
        operation: transition
        status: 'Resolve' 
