---
- name: Test
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather facts 
      shell: 'systemctl status httpd'
      register: httpd_status
      ignore_errors: true

    - name: Print service facts
      debug:
        msg: '{{ httpd_status.stdout_lines }}'
