---
- name: Listen for events on a webhook
  hosts: web
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - "http://172.27.40.13/"
        delay: 30
 
  rules:
    ## Define the action we should take should the condition be met
    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: 'Jira-EDA-SiteDown'
          organization: 'Default'
